\c electoral_db
insert into Constituency values ('const_001kar','st','Anekal','kar');
insert into Constituency values ('const_002ker','st','KOZHIKODE NORTH','ker');
insert into Constituency values ('const_003ker','ls','PALAKKAD','ker');
insert into Constituency values ('const_004ker','ls','WADAKKANCHERY','ker');
insert into Constituency values ('const_005ker','ls','THODUPUZHA','ker');
insert into Constituency values ('const_006kar','st','Vijayanagara','kar');
insert into Constituency values ('const_007mah','st','SAKOLI','mah');
insert into Constituency values ('const_008kar','ls','Govindraj','kar');
insert into Constituency values ('const_009ker','st','ANGAMALY','ker');
insert into Constituency values ('const_010tam','st','NAGAPATTINAM','tam');
insert into Constituency values ('const_011ker','st','MUVATTUPUZHA','ker');
insert into Constituency values ('const_012ker','ls','THRISSUR','ker');
insert into Constituency values ('const_013kar','ls','Nippani','kar');
insert into Constituency values ('const_014kar','st','Hassan','kar');
insert into Constituency values ('const_015ker','ls','TALIPARAMBA','ker');
insert into Constituency values ('const_016mah','ls','NANDED SOUTH','mah');
insert into Constituency values ('const_017mah','ls','AURANGABAD (WEST) (SC)','mah');
insert into Constituency values ('const_018tam','st','METTUPALAYAM','tam');
insert into Constituency values ('const_019tam','ls','CHEYYUR (SC)','tam');
insert into Constituency values ('const_020kar','ls','Holalkere','kar');
insert into Constituency values ('const_021kar','st','Chamarajanagar','kar');
insert into Constituency values ('const_022kar','ls','Gauribidanur','kar');
insert into Constituency values ('const_023mah','ls','SHRIRAMPUR (SC)','mah');
insert into Constituency values ('const_024kar','ls','Indi','kar');
insert into Constituency values ('const_025mah','ls','SAVNER','mah');
insert into Constituency values ('const_026tam','st','VALPARAI (SC)','tam');
insert into Constituency values ('const_027kar','st','Mangalore','kar');
insert into Constituency values ('const_028tam','st','PALLAVARAM','tam');
insert into Constituency values ('const_029ker','ls','KONDOTTY','ker');
insert into Constituency values ('const_030kar','ls','Maski','kar');
insert into Constituency values ('const_031kar','ls','Magadi','kar');
insert into Constituency values ('const_032kar','st','Dharwad','kar');
insert into Constituency values ('const_033kar','ls','Muddebihal','kar');
insert into Constituency values ('const_034kar','st','Maddur','kar');
insert into Constituency values ('const_035ker','st','VENGARA','ker');
insert into Constituency values ('const_036tam','st','NILAKKOTTAI (SC)','tam');
insert into Constituency values ('const_037kar','st','Chamrajpet','kar');
insert into Constituency values ('const_038tam','ls','KULITHALAI','tam');
insert into Constituency values ('const_039kar','ls','Jevargi','kar');
insert into Constituency values ('const_040mah','ls','KINWAT','mah');
insert into Constituency values ('const_041ker','st','KONNI','ker');
insert into Constituency values ('const_042mah','st','JAMNER','mah');
insert into Constituency values ('const_043tam','st','KILLIYOOR','tam');
insert into Constituency values ('const_044mah','st','DINDOSHI','mah');
insert into Constituency values ('const_045tam','ls','PERAMBUR','tam');
insert into Constituency values ('const_046kar','st','Yadgir','kar');
insert into Constituency values ('const_047kar','ls','Shravanabelagola','kar');
insert into Constituency values ('const_048ker','st','VAMANAPURAM','ker');
insert into Constituency values ('const_049mah','ls','KAMTHI','mah');
insert into Constituency values ('const_050tam','st','GOBICHETTIPALAYAM','tam');
insert into Constituency values ('const_051mah','st','KATOL','mah');
insert into Constituency values ('const_052mah','ls','LATUR CITY','mah');
insert into Constituency values ('const_053kar','ls','Koppal','kar');
insert into Constituency values ('const_054kar','st','Hanur','kar');
insert into Constituency values ('const_055ker','ls','AMBALAPUZHA','ker');
insert into Constituency values ('const_056ker','st','MANANTHAVADY','ker');
insert into Constituency values ('const_057tam','ls','MADURAI NORTH','tam');
insert into Constituency values ('const_058ker','st','PEERUMADE','ker');
insert into Constituency values ('const_059mah','st','GANSAVANGI','mah');
insert into Constituency values ('const_060kar','st','Shimoga','kar');
