\c electoral_db
insert into Constituency values ('const_001mah','st','CHARKOP','mah');
insert into Constituency values ('const_002mah','ls','BADNERA','mah');
insert into Constituency values ('const_003ker','st','KUTTANAD','ker');
insert into Constituency values ('const_004mah','st','AHERI (ST)','mah');
insert into Constituency values ('const_005kar','st','Gadag','kar');
insert into Constituency values ('const_006kar','ls','Sindagi','kar');
insert into Constituency values ('const_007mah','ls','AURANGABAD (WEST) (SC)','mah');
insert into Constituency values ('const_008kar','st','Shahapur','kar');
insert into Constituency values ('const_009mah','ls','DEGLUR (SC)','mah');
insert into Constituency values ('const_010kar','st','Mulbagal','kar');
insert into Constituency values ('const_011mah','ls','NEVASA','mah');
insert into Constituency values ('const_012kar','st','Shimoga','kar');
insert into Constituency values ('const_013kar','ls','Muddebihal','kar');
insert into Constituency values ('const_014tam','st','VEDHARANYAM','tam');
insert into Constituency values ('const_015kar','ls','Tumkur','kar');
insert into Constituency values ('const_016mah','st','BALLARPUR','mah');
insert into Constituency values ('const_017ker','ls','PAYYANNUR','ker');
insert into Constituency values ('const_018tam','ls','PALLAVARAM','tam');
insert into Constituency values ('const_019mah','ls','MUMBADEVI','mah');
insert into Constituency values ('const_020mah','ls','BHUSAWAL (SC)','mah');
insert into Constituency values ('const_021mah','st','GEORAI','mah');
insert into Constituency values ('const_022mah','ls','CHALISGAON','mah');
insert into Constituency values ('const_023ker','st','AROOR','ker');
insert into Constituency values ('const_024ker','ls','THRIKKAKARA','ker');
insert into Constituency values ('const_025mah','ls','SHIRPUR (ST)','mah');
insert into Constituency values ('const_026tam','st','THIRUMANGALAM','tam');
insert into Constituency values ('const_027kar','st','Harapanahalli','kar');
insert into Constituency values ('const_028mah','ls','SHRIRAMPUR (SC)','mah');
insert into Constituency values ('const_029kar','ls','Chamarajanagar','kar');
insert into Constituency values ('const_030mah','ls','NAWAPUR (ST)','mah');
