\c electoral_db
insert into Constituency values ('const_001mah','st','GONDIA','mah');
insert into Constituency values ('const_002tam','st','ATHOOR','tam');
insert into Constituency values ('const_003kar','st','Sarvagnanagar','kar');
insert into Constituency values ('const_004tam','st','THALLY','tam');
insert into Constituency values ('const_005mah','ls','BALLARPUR','mah');
insert into Constituency values ('const_006tam','st','THIRUMANGALAM','tam');
insert into Constituency values ('const_007kar','ls','Shahapur','kar');
insert into Constituency values ('const_008kar','ls','Sindhanur','kar');
insert into Constituency values ('const_009mah','ls','ASHTI','mah');
insert into Constituency values ('const_010mah','ls','BHOKAR','mah');
insert into Constituency values ('const_011kar','ls','Chiknayakanhalli','kar');
insert into Constituency values ('const_012mah','ls','AKOLA EAST','mah');
insert into Constituency values ('const_013kar','ls','Hebbal','kar');
insert into Constituency values ('const_014mah','st','DEGLUR (SC)','mah');
insert into Constituency values ('const_015mah','st','PARLI','mah');
insert into Constituency values ('const_016mah','ls','DHULE RURAL','mah');
insert into Constituency values ('const_017ker','st','KUTTANAD','ker');
insert into Constituency values ('const_018tam','ls','KATTUMANNARKOIL (SC)','tam');
insert into Constituency values ('const_019kar','st','Hoskote','kar');
insert into Constituency values ('const_020ker','ls','KALAMASSERY','ker');
insert into Constituency values ('const_021ker','st','PAYYANNUR','ker');
insert into Constituency values ('const_022mah','ls','AKKALKUWA (ST)','mah');
insert into Constituency values ('const_023kar','ls','Kanakapura','kar');
insert into Constituency values ('const_024ker','ls','NILAMBUR','ker');
insert into Constituency values ('const_025mah','ls','BASMATH','mah');
insert into Constituency values ('const_026kar','st','Varuna','kar');
insert into Constituency values ('const_027ker','st','WADAKKANCHERY','ker');
insert into Constituency values ('const_028ker','ls','KALPETTA','ker');
insert into Constituency values ('const_029mah','ls','DINDOSHI','mah');
insert into Constituency values ('const_030mah','st','BULDHANA','mah');
insert into Constituency values ('const_031ker','ls','VAMANAPURAM','ker');
insert into Constituency values ('const_032ker','st','PUTHUPPALLY','ker');
insert into Constituency values ('const_033tam','st','SIRKAZHI (SC)','tam');
insert into Constituency values ('const_034ker','st','PUTHUKKAD','ker');
insert into Constituency values ('const_035mah','ls','NAWAPUR (ST)','mah');
insert into Constituency values ('const_036ker','st','IRIKKUR','ker');
insert into Constituency values ('const_037kar','st','Sandur','kar');
insert into Constituency values ('const_038kar','ls','Humnabad','kar');
insert into Constituency values ('const_039tam','st','THIRU-VI-KA-NAGAR (SC)','tam');
insert into Constituency values ('const_040ker','ls','VATTIYOORKAVU','ker');
insert into Constituency values ('const_041kar','ls','Lingsugur','kar');
insert into Constituency values ('const_042mah','ls','SHAHADA (ST)','mah');
insert into Constituency values ('const_043kar','st','Davanagere','kar');
insert into Constituency values ('const_044mah','st','BADNERA','mah');
insert into Constituency values ('const_045mah','st','NANDURBAR (ST)','mah');
insert into Constituency values ('const_046kar','ls','Srinivaspur','kar');
insert into Constituency values ('const_047mah','ls','CHANDRAPUR (SC)','mah');
insert into Constituency values ('const_048kar','st','Doddaballapur','kar');
insert into Constituency values ('const_049ker','st','ERANAD','ker');
insert into Constituency values ('const_050kar','st','Shimoga','kar');
insert into Constituency values ('const_051ker','st','KOCHI','ker');
insert into Constituency values ('const_052ker','ls','KUTTIADI','ker');
insert into Constituency values ('const_053ker','ls','PERAMBRA','ker');
insert into Constituency values ('const_054tam','st','MADURAI CENTRAL','tam');
insert into Constituency values ('const_055tam','st','MADURAI EAST','tam');
insert into Constituency values ('const_056mah','ls','VILE PARLE','mah');
insert into Constituency values ('const_057tam','st','KAVUNDAMPALAYAM','tam');
insert into Constituency values ('const_058kar','ls','Gauribidanur','kar');
insert into Constituency values ('const_059mah','ls','KURLA (SC)','mah');
insert into Constituency values ('const_060ker','st','MANALUR','ker');
