\c electoral_db
insert into Party values ( 'par_001', 'null', 'Bharatiya Janata Party' , 'coal_01' );
insert into Party values ( 'par_002', 'null', 'Indian National Congress' , 'coal_02' );
insert into Party values ( 'par_003', 'null', 'Dravida Munnetra Kazhagam' , 'coal_03' );
insert into Party values ( 'par_004', 'null', 'All India Trinamool Congress' , 'coal_01' );
insert into Party values ( 'par_005', 'null', 'Yuvajana Sramika Rythu Congress Party' , 'coal_02' );
insert into Party values ( 'par_006', 'null', 'Shiv Sena' , 'coal_03' );
insert into Party values ( 'par_007', 'null', 'Janata Dal (United)' , 'coal_04' );
insert into Party values ( 'par_008', 'null', 'Biju Janata Dal' , 'coal_05' );
insert into Party values ( 'par_009', 'null', 'Bahujan Samaj Party' , 'coal_05' );
insert into Party values ( 'par_010', 'null', 'Telangana Rashtra Samithi' , 'coal_03' );
insert into Party values ( 'par_011', 'null', 'Lok Janshakti Party' , 'coal_02' );
insert into Party values ( 'par_012', 'null', 'Nationalist Congress Party' , 'coal_01' );
insert into Party values ( 'par_013', 'null', 'Samajwadi Party' , 'coal_01' );
insert into Party values ( 'par_014', 'null', 'Independent' , 'coal_04' );
insert into Party values ( 'par_015', 'null', 'Communist Party Of India (MARXIST)' , 'coal_04' );
insert into Party values ( 'par_016', 'null', 'Indian Union Muslim League' , 'coal_02' );
insert into Party values ( 'par_017', 'null', 'NC' , 'coal_01' );
insert into Party values ( 'par_018', 'null', 'Telugu Desam Party' , 'coal_05' );
insert into Party values ( 'par_019', 'null', 'Apna Dal (Soneylal)' , 'coal_04' );
insert into Party values ( 'par_020', 'null', 'All India Majlis-E-Ittehadul Muslimeen' , 'coal_02' );
